language: node_js
node_js:
  - 12
services:
  - mongodb
before_install:
  - export TZ=America/Chicago
before_script:
  - |
    cat > .env <<EOL
    APPLICATION_NAME=MemeMail
    APPLICATION_COOKIE_SECRET=secret
    APPLICATION_DATABASE_URL=mongodb://127.0.0.1:27017/mememail?readPreference=primary&ssl=false
    APPLICATION_FAILED_LOGIN_ATTEMPTS=3
    APPLICATION_FAILED_LOGIN_TIMEOUT=5
    APPLICATION_MASTER_USERNAME=test
    APPLICATION_MASTER_PASSWORD=test
    GOOGLE_CLIENT_ID=NULL
    GOOGLE_CLIENT_SECRET=NULL
    GOOGLE_REDIRECT_URL=http://localhost:3000/auth/google/callback
    GMAIL_API_KEY=NULL
    EOL
  - sleep 15